name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Deploy to FTP Server
        uses: juliaoldman0/ftp-action@main
        with:
          host: ftp.sspeterandpaulelizabeth.com
          username: lutron1
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: .
          remoteDir: /
          port: 21
          protocol: ftp
